#!/bin/bash

GREEN=$(tput setaf 10)
YELLOW=$(tput setaf 11)
NONE=$(tput sgr0)


recurse_bootstrap()
{
    echo "[${GREEN}${PWD}${NONE}] Running '${YELLOW}./bootstrap${NONE} ${@:2}' in '$1'"
    (cd "$1"  && ./bootstrap "${@:2}") || exit 1
}


recurse_bootstrap external/libevdevxx
recurse_bootstrap external/libgudevxx


announce_and_run()
{
    echo "[${GREEN}${PWD}${NONE}] Running '${YELLOW}$@${NONE}'"
    "$@" || exit 2
}


announce_and_run autoreconf --install --verbose "$@"


exit 0
