name: Build

on:

  # push:
  #   branches: [ "main" ]

  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: false

      # - name: Install dependencies
      #   uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libevdev-dev libgudev-1.0-dev libgtkmm-3.0-dev
      #     version: build

      - name: Install dependencies
        uses: gerlero/apt-install@v1
        with:
          packages: |
            autoconf
            automake
            autopoint
            intltool
            libevdev-dev
            libgtkmm-3.0-dev
            libgudev-1.0-dev
            libtool
            pkg-config

      - name: Install libevdevxx-static-devel
        run: |
          wget -q "https://github.com/dkosmari/libevdevxx/releases/download/v0.5.3/libevdevxx-static-dev_0.5.3-1_amd64.deb"
          sudo apt install -qy ./libevdevxx-static-dev_0.5.3-1_amd64.deb

      - name: Install libevdevxx-static-devel
        run: |
          wget -q "https://github.com/dkosmari/libgudevxx/releases/download/v0.3/libgudevxx-static-dev_0.3-1_amd64.deb"
          sudo apt install -qy ./libgudevxx-static-dev_0.3-1_amd64.deb

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Dist check
        run: make distcheck
