name: Build

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install dependencies
        uses: gerlero/apt-install@v1
        with:
          packages: |
            autoconf
            autoconf-archive
            automake
            autopoint
            intltool
            libevdev-dev
            libgtkmm-3.0-dev
            libgudev-1.0-dev
            libtool
            pkg-config

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Dist check
        run: make distcheck
