name: Debian 13 DEB package

on: [workflow_dispatch]

env:
  DISTRO: debian-13

jobs:
  build-deb:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Create docker image
      uses: docker/build-push-action@v6
      with:
        tags: image-${{ env.DISTRO }}
        context: ./packages/${{ env.DISTRO }}
      env:
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: Build DEB package
      uses: addnab/docker-run-action@v3
      with:
        image: image-${{ env.DISTRO }}
        options: --name container-${{ env.DISTRO }}
        run: |
          ./build.sh

    - name: Copy from container to host
      uses: tj-actions/docker-cp@v2
      with:
        container: container-${{ env.DISTRO }}
        source: /buildroot/output
        destination: packages/${{ env.DISTRO }}/

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DISTRO }} packages
        path: packages/${{ env.DISTRO }}/output
        if-no-files-found: error
